# Generated by Django 3.2.3 on 2021-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('status', models.BooleanField(default=True, verbose_name='Статус блокировки')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Время разблокировки')),
            ],
            options={
                'db_table': 'BanIp',
            },
        ),
    ]
